name: Node.js CI

on:
  push:
    branches: [ "develop_test" ]
  pull_request:
    branches: [ "develop_test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v4

    - name: Debug Paths
      run: find . -name 'package-lock.json'

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'

    - run: npm ci

    - run: npm start
