name: Node.js CI

on:
  push:
    branches: [ "develop_test" ]
  pull_request:
    branches: [ "develop_test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '/package-lock.json'

    - run: npm ci
      timeout-minutes: 10

    - run: npm run build --if-present
      timeout-minutes: 10

    - run: npm test
      timeout-minutes: 20
      env:
        CI: true # Ensures proper CI behavior
